#! /usr/bin/env python

APPNAME = 'Mix C'

srcdir = '.'
blddir = 'build'
llvmlibdir = '/usr/lib/llvm'

def set_options(opt):
	opt.tool_options('compiler_cxx')
	opt.tool_options('bison')
	opt.tool_options('flex')

def configure(conf):
	conf.check_tool('compiler_cxx')
	conf.check_tool('bison')
	conf.check_tool('flex')

	conf.env.append_value('BISONFLAGS', '-d')

def build(bld):
	bld.new_task_gen(
		features = 'cxx cstaticlib',
		cxxflags = [ '-ggdb' ],
		includes = [ 'include', 'build/default/src' ],
		source = 'src/parser.yc',
		target = 'parser')

	bld.new_task_gen(
		features = 'cxx cstaticlib',
		cxxflags = [ '-ggdb' ],
		includes = [ 'include', 'build/default/src' ],
		source = 'src/lexer.l',
		target = 'lexer')

	bld.new_task_gen(
		features = 'cxx cprogram',
		cxxflags = [ '-ggdb' ],
		includes = [ 'include', 'build/default/src' ],
		source = 'src/mixc.cc src/mixal.cc src/dotvisitor.cc src/symbolresolver.cc',
		uselib_local = 'parser lexer',
		target = 'mixc')
